### PR TITLE
minor edits

### PR DESCRIPTION
**Pull request by brianshumate**
These are just some first pass minor edits for readability with a minor correction or two.

Also trying to standardize the project name by shortening occurrences of "The Substance Composer" with just "Substance Composer".

### CODE REVIEW

**Comment by michael** [comment]
Thanks for the improvements. Will start to use "Substance Composer" consistently. Removing the "the" makes total sense.

**Comment by michael** [comment]
One thing that I want to work on is a diff viewer for substance documents. :)

For the start this could just be a web interface where you drop two versions of an article that should be compared.

**Comment by obuchtala** [comment]
Hmmm.. I don't think it is a very good idea to do this without operations. You will essentially have to reimplement many of those things...
Or you have to lower expectations to a minimum... i.e. only text diff...

**Comment by michael** [comment]
thought only about text diffs.. as a start...

**Comment by michael** [comment]
Given that storing the full operation history of docs is rather far away (and also expensive in terms of filesize) do you think it would be a good strategy to derive diffs as operations?

Like if I have A and A': 

What operations do I need to get from A to A'?

Then we could implement diff viewer on top of operations.

**Pull request merged**
